stages:
- name: ls
  steps:
  - runScriptConfig:
      image: busybox:latest
      shellScript: ls
  when:
    branch:
      exclude:
      - master
- name: test
  steps:
  - runScriptConfig:
      image: busybox:latest
      shellScript: sleep 5m
    envFrom:
    - sourceName: newsecret
      sourceKey: foobar
    - sourceName: newsecret
      sourceKey: foobar
      targetKey: fooalias
timeout: 1
