stages:
- name: ls
  steps:
  - runScriptConfig:
      image: busybox:latest
      shellScript: ls
  when:
    branch:
      exclude:
      - master
- name: test
  steps:
  - runScriptConfig:
      image: busybox:latest
      shellScript: |-
        echo "FOO: "
        echo $FOO
    env:
      FOO: bar
timeout: 60
