stages:
- name: ls
  steps:
  - runScriptConfig:
      image: busybox:latest
      shellScript: ls
  when:
    branch:
      exclude:
      - master
- name: test
  steps:
  - runScriptConfig:
      image: busybox:latest
      shellScript: |-
        ls
        ls
timeout: 60
branch:
  include:
  - master
